Repository upbound/homebrew-tap, pull requests merged in 2022-08, with the labels that each got.

#22 Update `up` and `docker-credential-up` to v0.12.1
  Formula/docker-credential-up.rb
  Formula/up.rb
Labels: size/M

#23 Update `up` and `docker-credential-up` to` v0.12.2`
  Formula/docker-credential-up.rb
  Formula/up.rb
Labels: size/L

#24 Update `up` and `docker-credential-up` to `v0.13.0`
  Formula/docker-credential-up.rb
  Formula/up.rb
Labels: size/M

#25 Add GitHub workflow to bump formula versions
  .github/bump-formula.rb
  .github/workflows/bump-formula.yaml
Labels: size/M

#26 Use `GITHUB_WORKSPACE` for repo root
  .github/bump-formula.rb
  .github/workflows/bump-formula.yaml
Labels: size/S
